fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref:  '4.20.0'
    python:
      repo: 'puppet/python'
      ref:  '2.2.2'
    systemd:
      repo: 'camptocamp/systemd'
      ref: '1.0.0'
  symlinks:
    airflow: "#{source_dir}"
